server:
  port: 8900
  servlet:
    context-path: /

logging:
  file: /log/javaLearning/springbootDemo.log
  level:
    root: info
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: xux21
      password: xuxia_01724552
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 5000