server:
  port: 8080
  servlet:
    context-path: /springBootDemo

logging:
  file: xxx.log
  level:
    root: info
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'

spring:
  datasource:
    druid:
      url: jdbc:mysql://xxx
      username: xxx
      password: xxx
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  redis:
    database: 0
    host: xxx
    port: xxx
    password: xxx
    timeout: 5000